[viewer]
    Title = "shgang's blog"
    Description = "ä¸€ä¸ªä¸“æ³¨äºè½¯ä»¶å¼€å‘æŠ€æœ¯åˆ†äº«çš„ç½‘ç«™"
    Logo = "/resource/images/logo.jpg"
    Navigation = ["é¦–é¡µ", "/", "Goè¯­è¨€", "/slug/golang", "å½’æ¡£", "/pigeonhole", "å…³äº", "/about"]
    Github = "https://github.com/shgang97"
    Bilibili = "https://space.bilibili.com/371056419"
    Zhihu = "https://space.bilibili.com/371056419"
    Avatar = "/resource/images/personal-avatar.png"
    UserName = "shgang"
    UserDesc = "åç«¯å¼€å‘/å›½é™…ç±³å…°çƒè¿·<br/>a self-taught passionate Java developer from ChinağŸ‡¨ğŸ‡³"
[system]
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
	QiniuAccessKey = "s7XYXd9Z6TqeL7l2M4PEfs8kbhlVsuP9W9H6RnOm"
	QiniuSecretKey = "CNYUlFTarXay7gieYLcl5-lkbemcsBPCdfBfuurf"
	Valine = true
	ValineAppId = "I5KYvHhNhJpxeu2P0qY1oU7O-gzGzoHsz"
	ValineAppKey = "JG2lVoNKxgLFPj7lrb2VVgtr"
	ValineServerURL = "https://i5kyvhhn.lc-cn-n1-shared.com"