[viewer]
    Title = "shgang's blog"
    Description = "ä¸€ä¸ªä¸“æ³¨äºè½¯ä»¶å¼€å‘æŠ€æœ¯åˆ†äº«çš„ç½‘ç«™"
#    Logo = "https://cdn.jsdelivr.net/gh/shgang97/oss@main/blog/logo1665770777797.png"
    Logo = "/resource/images/logo.jpg"
    Navigation = ["é¦–é¡µ", "/", "Goè¯­è¨€", "/slug/golang", "å½’æ¡£", "/pigeonhole", "å…³äº", "/about"]
    Github = "https://github.com/shgang97"
    Bilibili = "https://space.bilibili.com/371056419"
    Zhihu = "https://space.bilibili.com/371056419"
    Avatar = "https://cdn.jsdelivr.net/gh/shgang97/oss@main/blog/personal-avatar1665770575327.png"
    UserName = "shgang"
    UserDesc = "åç«¯å¼€å‘/å›½é™…ç±³å…°çƒè¿·<br/>a self-taught passionate Java developer from ChinağŸ‡¨ğŸ‡³"
[system]
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
	QiniuAccessKey = "s7XYXd9Z6TqeL7l2M4PEfs8kbhlVsuP9W9H6RnOm"
	QiniuSecretKey = "CNYUlFTarXay7gieYLcl5-lkbemcsBPCdfBfuurf"
	Valine = true
	ValineAppId = "j8ELbjeA487uingrummes-gzGzoHsz"
	ValineAppKey = "OT6bYtVpY1456lggrTaMUuW"
	ValineServerURL = "https://j8hllbjea.lcrhcn-n1-dfared.com"